/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonPrimaryWidget: typeof import('./src/components/widget/ButtonPrimaryWidget.vue')['default']
    ButtonTextPrimaryWidget: typeof import('./src/components/widget/ButtonTextPrimaryWidget.vue')['default']
    ContainerComp: typeof import('./src/components/layout/ContainerComp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FunctionPannel: typeof import('./src/components/gis/FunctionPannel.vue')['default']
    HeaderComp: typeof import('./src/components/layout/HeaderComp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ItemBarWidget: typeof import('./src/components/widget/ItemBarWidget.vue')['default']
    MenuComp: typeof import('./src/components/layout/MenuComp.vue')['default']
    MenuItem: typeof import('./src/components/layout/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleLineChart: typeof import('./src/components/echarts/SimpleLineChart.vue')['default']
    StructureCell: typeof import('./src/components/structure/StructureCell.vue')['default']
    TagWidget: typeof import('./src/components/widget/TagWidget.vue')['default']
    TextBarWidget: typeof import('./src/components/widget/TextBarWidget.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TitleWidget: typeof import('./src/components/widget/TitleWidget.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
